{% set name = "matchpoint" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matchpoint-{{ version }}.tar.gz
  sha256: 8cf512bb5f7e0c92188c2b7954ac3fc5ee75422d417642817418d745d5ace2b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22, <1.25
    - matplotlib-base >=3.5
    - pathlib2
    - pyyaml >=6.0
    - scikit-image >=0.19,<=0.20
    - scipy >=1.8
    - scikit-learn >=1.0
    - shapely >=1.8
    - tqdm
    - xarray >=2023

test:
  imports:
    - matchpoint
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Chirlmin-Joo-lab/matchpoint
  summary: A package for performing point set registration.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://matchpoint.readthedocs.io/
  dev_url: https://github.com/Chirlmin-Joo-lab/matchpoint

extra:
  recipe-maintainers:
    - ivoseverins
