context:
  name: 'matchpoint'
  version: "1.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/matchpoint-${{ version }}.tar.gz
  sha256: 026483810da7cb9667dcf4fc562c9800be4c158937c6390dadeaedaba25ec312

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=61.0.0
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python
    - numpy >=1.22
    - matplotlib-base >=3.5
    - pyyaml >=6.0
    - scikit-image >=0.21
    - scipy >=1.8
    - scikit-learn >=1.0
    - shapely >=1.8
    - tqdm
    - xarray >=2024.07

tests:
  imports:
    - matchpoint
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  homepage: https://github.com/Chirlmin-Joo-lab/matchpoint
  summary: A package for performing point set registration.
  license: GPL-3.0-or-later
  license_file: LICENSE
  documentation: https://matchpoint.readthedocs.io/
  repository: https://github.com/Chirlmin-Joo-lab/matchpoint

extra:
  recipe-maintainers:
    - ivoseverins
